# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sensel/common/v1/common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sensel/common/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dsensel/common/v1/common.proto\x12\x10sensel.common.v1\x1a\x1fgoogle/protobuf/timestamp.proto\")\n\x08Producer\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\"\xd7\x01\n\tEventMeta\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x11\n\ttenant_id\x18\x02 \x01(\t\x12\x0f\n\x07site_id\x18\x03 \x01(\t\x12\x11\n\tsensor_id\x18\x04 \x01(\t\x12/\n\x0bobserved_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08sequence\x18\x06 \x01(\x04\x12\x10\n\x08trace_id\x18\x07 \x01(\t\x12,\n\x08producer\x18\x08 \x01(\x0b\x32\x1a.sensel.common.v1.Producer\"\xb1\x01\n\x11\x45videnceAttribute\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x16\n\x0cstring_value\x18\x02 \x01(\tH\x00\x12\x13\n\tint_value\x18\x03 \x01(\x12H\x00\x12\x16\n\x0c\x64ouble_value\x18\x04 \x01(\x01H\x00\x12\x14\n\nbool_value\x18\x05 \x01(\x08H\x00\x12\x15\n\x0b\x62ytes_value\x18\x06 \x01(\x0cH\x00\x12\x14\n\njson_value\x18\x07 \x01(\tH\x00\x42\x07\n\x05valueb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensel.common.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCER']._serialized_start=84
  _globals['_PRODUCER']._serialized_end=125
  _globals['_EVENTMETA']._serialized_start=128
  _globals['_EVENTMETA']._serialized_end=343
  _globals['_EVIDENCEATTRIBUTE']._serialized_start=346
  _globals['_EVIDENCEATTRIBUTE']._serialized_end=523
# @@protoc_insertion_point(module_scope)
